Online Test System/Controllers/DashBoardController.cs
using OfficeOpenXml;
using OfficeOpenXml.Style;
using Online_Test_System.BAL;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static Online_Test_System.Models.DashboardModel;

namespace Online_Test_System.Controllers
{
    public class DashBoardController : Controller
    {
        private readonly IDashboardBAL _IDashboardBAL;

        public DashBoardController()
        {
            _IDashboardBAL = new DashboardBAL();
        }
        // GET: DashBoard
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult AddQuestions()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddQuestions(QuestionModel model)
        {
            _IDashboardBAL.AddQuestionForTest(model);
            return View();
        }

        public ActionResult TestResult()
        {
            return View(_IDashboardBAL.GetTestResult().ToList());
        }

        public void ExportExcel()
        {
            List<TestResult> result = _IDashboardBAL.GetTestResult().ToList();

            ExcelPackage pck = new ExcelPackage();
            ExcelWorksheet ws = pck.Workbook.Worksheets.Add("TestResult");
            ws.Cells["A1:C1"].Style.Fill.PatternType = OfficeOpenXml.Style.ExcelFillStyle.Solid;
            ws.Cells["A1:C1"].Style.Fill.BackgroundColor.SetColor(ColorTranslator.FromHtml(string.Format("Yellow")));
            for (int i = 1; i <= result.Count() + 1; i++)
            {
                ws.Cells["A" + i + ":" + "C" + i].Style.Border.Top.Style = ExcelBorderStyle.Thin;
                ws.Cells["A" + i + ":" + "C" + i].Style.Border.Right.Style = ExcelBorderStyle.Thin;
                ws.Cells["A" + i + ":" + "C" + i].Style.Border.Bottom.Style = ExcelBorderStyle.Thin;
                ws.Cells["A" + i + ":" + "C" + i].Style.Border.Left.Style = ExcelBorderStyle.Thin;
            }
            ws.Cells["A1"].Value = "Student Name";
            ws.Cells["B1"].Value = "Total Score";
            ws.Cells["C1"].Value = "Student Score";

            int row = 2;
            foreach (var item in result)
            {
                ws.Cells[string.Format("A{0}", row)].Value = item.StudentName;
                ws.Cells[string.Format("B{0}", row)].Value = item.TestScore;
                ws.Cells[string.Format("C{0}", row)].Value = item.TotalQuestions;
                row++;
            }
            ws.Cells["A:AZ"].AutoFitColumns();
            Response.Clear();
            Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
            Response.AddHeader("content-disposition", "attachment; filename=StudentTestResult.xlsx");
            Response.BinaryWrite(pck.GetAsByteArray());
            Response.End();
        }

    }
}

Online Test System/Views/DashBoard/AddQuestions.cshtml
@{
    ViewBag.Title = "Questions";
}

<h2>Add Question For Test</h2>
@using (Html.BeginForm("AddQuestions", "DashBoard", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
<form id="AddQuestion">
    <label>Question:</label>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
    <textarea id="Question" name="Question"></textarea>
    <br>
    <br>
    <label>Answer1:</label>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
    <input type="text" id="Answer1" name="Answer1">
    <br>
    <br>
    <label>Answer2:</label>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
    <input type="text" id="Answer2" name="Answer2">
    <br>
    <br>
    <label>Answer3:</label>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
    <input type="text" id="Answer3" name="Answer3">
    <br>
    <br>
    <label>Answer4:</label>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
    <input type="text" id="Answer4" name="Answer4">
    <br>
    <br>
    <label>Correct Answer:</label>&nbsp;&nbsp; <b>Answer1</b>
    <input type="radio" id="CorrectAnswer" value="1" name="CorrectAnswer">
    <b>Answer2</b>
    <input type="radio" id="CorrectAnswer" value="2" name="CorrectAnswer">
    <b>Answer3</b>
    <input type="radio" id="CorrectAnswer" value="3" name="CorrectAnswer">
    <b>Answer4</b>
    <input type="radio" id="CorrectAnswer" value="4" name="CorrectAnswer">
    <br>
    <br>
    <button class="btn btn-primary btn-lg btn-block">Add</button>
</form>
}

Online Test System/Views/DashBoard/Index.cshtml
@{
    ViewBag.Title = "Dashboard";
}

<input type="button" value="Add Questions for Test" onclick="location.href='@Url.Action("AddQuestions", "DashBoard")'" />
<input type="button" value="View Students Test Result" onclick="location.href='@Url.Action("TestResult", "DashBoard")'" / />

Online Test System/Views/DashBoard/TestResult.cshtml
@model IEnumerable<Online_Test_System.Models.DashboardModel.TestResult>
@{
    ViewBag.Title = "TestResult";
}
<h2>TestResult</h2>
<button type="button" class="btn btn-info" onclick="location.href='@Url.Action("ExportExcel", "DashBoard")'">Export To Excel</button>
<br />
<br />
<table class="table" border="1" id="DataTable">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.StudentName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalQuestions)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TestScore)
            </th>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @item.StudentName
                </td>
                <td>
                    @item.TotalQuestions
                </td>
                <td>
                    @item.TestScore
                </td>
            </tr>
        }
    </tbody>

</table>